repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  # VÃ¤lj en stabil version du har installerad, t.ex. v17.0.6 eller v18.x
  rev: v21.1.2

  hooks:

    - id: clang-format
      # Matcha Arduino/C++-filer
      files: "\\.(c|h)$"
      # Se till att .ino tolkas som C++
      args: ["--style=file", "--assume-filename=.c"]